# Generated by Django 5.0.3 on 2024-04-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_gallery', '0002_tag_image_description_image_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(related_name='images', to='images_gallery.tag'),
        ),
    ]
