CREATE TABLE prace (
	ID INTEGER PRIMARY KEY,
	Tytul TEXT NOT NULL,
	Rok INTEGER NOT NULL,
	Autorzy INTEGER NOT NULL,
	Punkty INTEGER NOT NULL
);


INSERT INTO prace VALUES (1, 'Function definitions for compound values in object-oriented languages', 2017, 2, 70);
INSERT INTO prace VALUES (2, 'Regular Separability of Parikh Automata', 2017, 4, 140);
INSERT INTO prace VALUES (3, 'Separability of Reachability Sets of Vector Addition Systems', 2017, 4, 140);
INSERT INTO prace VALUES (4, 'Timed pushdown automata and branching vector addition systems', 2017, 4, 200);
INSERT INTO prace VALUES (5, 'Regular separability of one counter automata', 2017, 2, 200);
INSERT INTO prace VALUES (6, 'Rule-Based Reasoning with Belief Structures', 2017, 3, 20);
INSERT INTO prace VALUES (7, 'Heterogeneous Approximate Reasoning with Graded Truth Values', 2017, 4, 20);
INSERT INTO prace VALUES (8, 'The Spectrum of Equilibria for the Colonel Blotto and the Colonel Lotto Games', 2017, 1, 70);
INSERT INTO prace VALUES (9, 'Detecting Locus Acquisition Events in Gene Trees', 2017, 3, 70);
INSERT INTO prace VALUES (10, 'New Algorithms for the Genomic Duplication Problem', 2017, 2, 70);
INSERT INTO prace VALUES (11, 'Bounding Average-Energy Games', 2017, 5, 140);
INSERT INTO prace VALUES (12, 'On B\üchi One-Counter Automata', 2017, 4, 140);
INSERT INTO prace VALUES (13, 'Linear combinations of unordered data vectors', 2017, 3, 200);
INSERT INTO prace VALUES (14, 'SMIS 2017 Data Mining Competition: Trading Based on Recommendations', 2017, 7, 20);
INSERT INTO prace VALUES (15, 'Decremental Single-source Reachability in Planar Digraphs', 2017, 4, 200);
INSERT INTO prace VALUES (16, 'Contracting a Planar Graph Efficiently', 2017, 6, 140);
INSERT INTO prace VALUES (17, 'Modal mu-Calculus with Atoms', 2017, 2, 70);
INSERT INTO prace VALUES (18, 'Expressiveness of Probabilistic Modal Logics, Revisited', 2017, 3, 140);
INSERT INTO prace VALUES (19, 'Learning nominal automata', 2017, 5, 200);
INSERT INTO prace VALUES (20, 'Efficient Enumeration of Non-Equivalent Squares in Partial Words with Few Holes', 2017, 8, 140);
INSERT INTO prace VALUES (21, 'LOIS: Syntax and Semantics', 2017, 2, 200);
INSERT INTO prace VALUES (22, 'On the Computational Complexity of Gossip Protocols', 2017, 3, 200);
INSERT INTO prace VALUES (23, 'Programming Languages in GitHub: A Visualization in Hyperbolic Plane', 2017, 2, 20);
INSERT INTO prace VALUES (24, 'Improving TSP Tours Using Dynamic Programming over Tree Decompositions', 2017, 3, 140);
INSERT INTO prace VALUES (25, 'Approximation and Parameterized Complexity of Minimax Approval Voting', 2017, 4, 200);
INSERT INTO prace VALUES (26, 'Tight Lower Bounds for the Complexity of Multicoloring', 2017, 5, 140);
INSERT INTO prace VALUES (27, 'A Fast Deterministic Detection of Small Pattern Graphs in Graphs Without Large Cliques', 2017, 2, 20);
INSERT INTO prace VALUES (28, 'Axiomatic Characterization of Game-Theoretic Network Centralities', 2017, 3, 200);
INSERT INTO prace VALUES (29, 'The Dollar Auction with Spiteful Players', 2017, 4, 200);
INSERT INTO prace VALUES (30, 'On the Construction of Covert Networks', 2017, 4, 200);
INSERT INTO prace VALUES (31, 'Strategic Social Network Analysis', 2017, 3, 200);
INSERT INTO prace VALUES (32, 'Dynamic Beats Fixed: On Phase-Based Algorithms for File Migration', 2017, 3, 140);
INSERT INTO prace VALUES (33, 'On Problems Equivalent to (min, +)-Convolution', 2017, 4, 140);
INSERT INTO prace VALUES (34, 'Bisimilarity for paraconsistent description logics', 2017, 4, 70);
INSERT INTO prace VALUES (35, 'Why Do Cascade Sizes Follow a Power-Law?', 2017, 4, 200);
INSERT INTO prace VALUES (36, 'Approximation and Kernelization for Chordal Vertex Deletion', 2017, 2, 200);
INSERT INTO prace VALUES (37, 'Edge Bipartization Faster Than 2^k', 2017, 3, 70);
INSERT INTO prace VALUES (38, 'Subexponential Parameterized Algorithms for Graphs of Polynomial Growth', 2017, 2, 140);
INSERT INTO prace VALUES (39, 'Exploring the Complexity of Layout Parameters in Tournaments and Semi-Complete Digraphs', 2017, 3, 140);
INSERT INTO prace VALUES (40, 'Model-checking for successor-invariant first-order formulas on graph classes of bounded expansion', 2017, 6, 200);
INSERT INTO prace VALUES (41, 'Optimizing Tree Decompositions in MSO', 2017, 2, 140);
INSERT INTO prace VALUES (42, 'Linear Kernels for Edge Deletion Problems to Immersion-Closed Graph Classes', 2017, 5, 140);
INSERT INTO prace VALUES (43, 'Fully polynomial-time parameterized computations for graphs and matrices of low treewidth', 2017, 5, 200);
INSERT INTO prace VALUES (44, 'Cutwidth: Obstructions and Algorithmic Aspects', 2017, 5, 70);
INSERT INTO prace VALUES (45, 'Neighborhood Complexity and Kernelization for Nowhere Dense Classes of Graphs', 2017, 7, 140);
INSERT INTO prace VALUES (46, 'Approximation and Parameterized Algorithms for Geometric Independent Set with Shrinking', 2017, 3, 140);
INSERT INTO prace VALUES (47, 'On Low Rank-Width Colorings', 2017, 3, 140);
INSERT INTO prace VALUES (48, 'Streaming K-Mismatch with Error Correcting and Applications', 2017, 2, 200);
INSERT INTO prace VALUES (49, 'Palindromic Decompositions with Gaps and Errors', 2017, 5, 20);
INSERT INTO prace VALUES (50, 'Longest Common Factor After One Edit Operation', 2017, 5, 70);
INSERT INTO prace VALUES (51, 'Faster Algorithms for 1-Mappability of a Sequence', 2017, 6, 70);
INSERT INTO prace VALUES (52, 'Optimizing egalitarian performance in the side-effects model of colocation for data center resource management', 2017, 2, 140);
INSERT INTO prace VALUES (53, 'Negative-Weight Shortest Paths and Unit Capacity Minimum Cost Flow in Õ(m^10/7 log W) Time', 2017, 4, 200);
INSERT INTO prace VALUES (54, 'Improved Distance Queries and Cycle Counting by Frobenius Normal Form', 2017, 2, 140);
INSERT INTO prace VALUES (55, 'Approximate Nearest Neighbors Search Without False Negatives For l_2 For c>sqrtloglogn', 2017, 2, 140);
INSERT INTO prace VALUES (56, 'Automata Theory Approach to Predicate Intuitionistic Logic', 2017, 2, 70);
INSERT INTO prace VALUES (57, 'Attachment Centrality for Weighted Graphs', 2017, 2, 200);
INSERT INTO prace VALUES (58, 'Connecting Decidability and Complexity for MSO Logic', 2017, 1, 70);
INSERT INTO prace VALUES (59, 'A Characterisation of Pi\^0\_2 Regular Tree Languages', 2017, 3, 140);
INSERT INTO prace VALUES (60, 'Scalable Machine Learning with Granulated Data Summaries: A Case of Feature Selection', 2017, 3, 20);
INSERT INTO prace VALUES (61, 'When the Optimum is also Blind: a New Perspective on Universal Optimization', 2017, 4, 140);
INSERT INTO prace VALUES (62, 'Binary Reachability of Timed Pushdown Automata via Quantifier Elimination and Cyclic Order Atoms', 2018, 2, 140);
INSERT INTO prace VALUES (63, 'Online Facility Location with Deletions', 2018, 4, 140);
INSERT INTO prace VALUES (64, 'Universal Trees Grow Inside Separating Automata: Quasi-Polynomial Lower Bounds for Parity Games', 2018, 6, 200);
INSERT INTO prace VALUES (65, 'Unboundedness Problems for Languages of Vector Addition Systems', 2018, 3, 140);
INSERT INTO prace VALUES (66, 'Regular Separability of Well-Structured Transition Systems', 2018, 6, 140);
INSERT INTO prace VALUES (67, 'FairSwap: How To Fairly Exchange Digital Goods', 2018, 3, 200);
INSERT INTO prace VALUES (68, 'General State Channel Networks', 2018, 3, 200);
INSERT INTO prace VALUES (69, 'Individual Security and Network Design with Malicious Nodes', 2018, 3, 200);
INSERT INTO prace VALUES (70, 'The Wasserstein Distance as a Dissimilarity Measure for Mass Spectra with Application to Spectral Deconvolution', 2018, 6, 70);
INSERT INTO prace VALUES (71, 'Cophenetic Distances: A Near-Linear Time Algorithmic Framework', 2018, 3, 140);
INSERT INTO prace VALUES (72, 'Linear Equations with Ordered Data', 2018, 2, 140);
INSERT INTO prace VALUES (73, 'The IPv6 Routing Protocol for Low-power and Lossy Networks (RPL) under Network Partitions', 2018, 2, 140);
INSERT INTO prace VALUES (74, 'Ad Hoc 802.11-802.15.4 Crosstalk-Based Communication in Practice', 2018, 3, 140);
INSERT INTO prace VALUES (75, 'On Designing Provably Correct DODAG Formation Criteria for the IPv6 Routing Protocol for Low-Power and Lossy Networks (RPL)', 2018, 2, 70);
INSERT INTO prace VALUES (76, 'A Distributed Systems Perspective on Industrial IoT', 2018, 1, 140);
INSERT INTO prace VALUES (77, 'Investigating Similarity between Hearthstone Cards: Text Embeddings and Interchangeability Approaches', 2018, 2, 70);
INSERT INTO prace VALUES (78, 'Improving Hearthstone AI by Combining MCTS and Supervised Learning Algorithms', 2018, 3, 20);
INSERT INTO prace VALUES (79, 'Decremental Transitive Closure and Shortest Paths for Planar Digraphs and Beyond', 2018, 1, 200);
INSERT INTO prace VALUES (80, 'Optimal Dynamic Strings', 2018, 5, 200);
INSERT INTO prace VALUES (81, 'Improved Bounds for Shortest Paths in Dense Distance Graphs', 2018, 2, 140);
INSERT INTO prace VALUES (82, 'Decremental SPQR-trees for Planar Graphs', 2018, 5, 140);
INSERT INTO prace VALUES (83, 'On Periodicity Lemma for Partial Words', 2018, 4, 20);
INSERT INTO prace VALUES (84, 'Faster Recovery of Approximate Periods over Edit Distance', 2018, 6, 70);
INSERT INTO prace VALUES (85, 'Linear-Time Algorithm for Long LCF with k Mismatches', 2018, 8, 70);
INSERT INTO prace VALUES (86, 'String Periods in the Order-Preserving Model', 2018, 6, 140);
INSERT INTO prace VALUES (87, 'Efficient Computation of Sequence Mappability', 2018, 7, 70);
INSERT INTO prace VALUES (88, 'On Directed Feedback Vertex Set Parameterized by Treewidth', 2018, 6, 140);
INSERT INTO prace VALUES (89, 'WQO Dichotomy for 3-Graphs', 2018, 2, 140);
INSERT INTO prace VALUES (90, 'Quantifying Algorithmic Improvements over Time', 2018, 6, 200);
INSERT INTO prace VALUES (91, 'Finite Query Answering in Expressive Description Logics with Transitive Roles', 2018, 3, 200);
INSERT INTO prace VALUES (92, 'On Fuzzy Sheffer Stroke Operation', 2018, 6, 20);
INSERT INTO prace VALUES (93, 'Recursion Schemes and the WMSO+U Logic', 2018, 1, 140);
INSERT INTO prace VALUES (94, 'The Complexity of the Diagonal Problem for Recursion Schemes', 2018, 1, 70);
INSERT INTO prace VALUES (95, 'An Improved FPT Algorithm for Independent Feedback Vertex Set', 2018, 2, 140);
INSERT INTO prace VALUES (96, 'On Subexponential Parameterized Algorithms for Steiner Tree and Directed Subset TSP on Planar Graphs', 2018, 3, 200);
INSERT INTO prace VALUES (97, 'Experimental Evaluation of Parameterized Algorithms for Feedback Vertex Set', 2018, 2, 70);
INSERT INTO prace VALUES (98, 'Finding Hamiltonian Cycle in Graphs of Bounded Treewidth: Experimental Evaluation', 2018, 2, 70);
INSERT INTO prace VALUES (99, 'Empirical Evaluation of Approximation Algorithms for Generalized Graph Coloring and Uniform Quasi-Wideness', 2018, 5, 70);
INSERT INTO prace VALUES (100, 'First-Order Interpretations of Bounded Expansion Classes', 2018, 7, 140);
INSERT INTO prace VALUES (101, 'Quasi-Polynomial Time Approximation Schemes for Packing and Covering Problems in Planar Graphs', 2018, 3, 140);
INSERT INTO prace VALUES (102, 'Parameterized circuit complexity of model-checking on sparse structures', 2018, 3, 200);
INSERT INTO prace VALUES (103, 'Definable decompositions for graphs of bounded linear cliquewidth', 2018, 3, 200);
INSERT INTO prace VALUES (104, 'On the number of types in sparse graphs', 2018, 3, 200);
INSERT INTO prace VALUES (105, 'Broadcast with Energy-Exchanging Mobile Agents Distributed on a Tree', 2018, 4, 70);
INSERT INTO prace VALUES (106, 'Dfuntest: A Testing Framework for Distributed Applications', 2018, 2, 20);
INSERT INTO prace VALUES (107, 'Collective Schedules: Scheduling Meets Computational Social Choice', 2018, 3, 200);
INSERT INTO prace VALUES (108, 'Reducing Transducer Equivalence to Register Automata Problems Solved by "Hilbert Method', 2018, 3, 70);
INSERT INTO prace VALUES (109, 'Approval-Based Multi-Winner Rules and Strategic Voting', 2018, 2, 200);
INSERT INTO prace VALUES (110, 'Consistent Approval-Based Multi-Winner Rules', 2018, 2, 200);
INSERT INTO prace VALUES (111, 'Stable Marriage with Multi-Modal Preferences', 2018, 3, 200);
INSERT INTO prace VALUES (112, 'Multiwinner Elections With Diversity Constraints', 2018, 5, 200);
INSERT INTO prace VALUES (113, 'On the Complexity of Extended and Proportional Justified Representation', 2018, 6, 200);
INSERT INTO prace VALUES (114, 'Proportional Approval Voting, Harmonic k-median, and Negative Association', 2018, 3, 140);
INSERT INTO prace VALUES (115, 'How Deterministic are Good-For-Games Automata?', 2018, 3, 70);
INSERT INTO prace VALUES (116, 'Unambiguous Languages Exhaust the Index Hierarchy', 2018, 1, 140);
INSERT INTO prace VALUES (117, 'Investigating Similarity between Hearthstone Cards: Text Embeddings and Interchangeability Approaches', 2018, 2, 70);
INSERT INTO prace VALUES (118, 'Ranking mutual information dependencies in a summary-based approximate analytics framework', 2018, 3, 70);
INSERT INTO prace VALUES (119, 'On computability and tractability for infinite sets', 2018, 2, 200);
INSERT INTO prace VALUES (120, 'An Axiomatization of the Eigenvector and Katz Centralities', 2018, 2, 200);
INSERT INTO prace VALUES (121, 'Axiomatization of the PageRank Centrality', 2018, 2, 200);
INSERT INTO prace VALUES (122, 'Random Order Contention Resolution Schemes', 2018, 2, 200);
INSERT INTO prace VALUES (123, 'Multi3Net: Segmenting Flooded Buildings via Fusion of Multiresolution, Multisensor, and Multitemporal Satellite Imagery', 2019, 7, 200);
INSERT INTO prace VALUES (124, 'String-to-String Interpretations With Polynomial-Size Output', 2019, 3, 140);
INSERT INTO prace VALUES (125, 'A non-regular language of infinite trees that is recognizable by a sort-wise finite algebra', 2019, 2, 70);
INSERT INTO prace VALUES (126, 'Regular tree languages in low levels of the Wadge Hierarchy', 2019, 4, 70);
INSERT INTO prace VALUES (127, 'MSO+\(\nabla\) is undecidable', 2019, 3, 200);
INSERT INTO prace VALUES (128, 'Occupational injury risk wage premium', 2019, 2, 140);
INSERT INTO prace VALUES (129, 'Timed Basic Parallel Processes', 2019, 3, 140);
INSERT INTO prace VALUES (130, 'Efficient reduction of nondeterministic automata with application to language inclusion testing', 2019, 2, 70);
INSERT INTO prace VALUES (131, 'Binary Reachability of Timed-register Pushdown Automata and Branching Vector Addition Systems', 2019, 4, 100);
INSERT INTO prace VALUES (132, 'On Problems Equivalent to (min, +)-Convolution', 2019, 4, 140);
INSERT INTO prace VALUES (133, 'Improving TSP Tours Using Dynamic Programming over Tree Decompositions', 2019, 3, 140);
INSERT INTO prace VALUES (134, 'Minimum Bisection Is Fixed-Parameter Tractable', 2019, 5, 200);
INSERT INTO prace VALUES (135, 'Applying deep learning to right whale photo identification', 2019, 6, 140);
INSERT INTO prace VALUES (136, 'Shortest paths in one-counter systems', 2019, 5, 70);
INSERT INTO prace VALUES (137, 'Regular Separability of One Counter Automata', 2019, 2, 70);
INSERT INTO prace VALUES (138, 'The Reachability Problem for Petri Nets is Not Elementary', 2019, 5, 200);
INSERT INTO prace VALUES (139, 'New Pumping Technique for 2-Dimensional VASS', 2019, 4, 140);
INSERT INTO prace VALUES (140, 'Improved Bounds for the Excluded-Minor Approximation of Treedepth', 2019, 3, 140);
INSERT INTO prace VALUES (141, 'Energy-optimal broadcast and exploration in a tree using mobile agents', 2019, 4, 100);
INSERT INTO prace VALUES (142, 'qDSB-Seq is a general method for genome-wide quantification of DNA double-strand breaks using sequencing', 2019, 12, 200);
INSERT INTO prace VALUES (143, 'A paraconsistent approach to actions in informationally complex environments', 2019, 3, 40);
INSERT INTO prace VALUES (144, 'Belief Shadowing', 2019, 3, 70);
INSERT INTO prace VALUES (145, 'Doxastic Group Reasoning via Multiple Belief Shadowing', 2019, 3, 70);
INSERT INTO prace VALUES (146, 'BDI Model of Connected and Autonomous Vehicles', 2019, 2, 20);
INSERT INTO prace VALUES (147, 'Simple Refreshing in the Noisy Leakage Model', 2019, 3, 140);
INSERT INTO prace VALUES (148, 'Unifying Leakage Models: From Probing Attacks to Noisy Leakage', 2019, 3, 100);
INSERT INTO prace VALUES (149, 'Perun: Virtual Payment Hubs over Cryptocurrencies', 2019, 4, 200);
INSERT INTO prace VALUES (150, 'Multi-party Virtual State Channels', 2019, 5, 200);
INSERT INTO prace VALUES (151, 'Progressive Algorithms for Domination and Independence', 2019, 4, 140);
INSERT INTO prace VALUES (152, 'Jaccard/Tanimoto similarity test and estimation methods for biological presence-absence data', 2019, 4, 100);
INSERT INTO prace VALUES (153, 'Automatic mapping of atoms across both simple and complex chemical reactions', 2019, 9, 200);
INSERT INTO prace VALUES (154, 'Biologically sound formal model of Hsp70 heat induction', 2019, 5, 70);
INSERT INTO prace VALUES (155, 'MIND: A double-linear model to accurately determine monoisotopic precursor mass in high-resolution top-down proteomics', 2019, 10, 140);
INSERT INTO prace VALUES (156, 'Truncated Robust Principal Component Analysis and Noise Reduction for Single Cell RNA Sequencing Data', 2019, 4, 70);
INSERT INTO prace VALUES (157, 'masstodon: A tool for assigning peaks and modeling electron transfer reactions in top-down mass spectrometry', 2019, 7, 140);
INSERT INTO prace VALUES (158, 'Mapping of breakpoints in balanced chromosomal translocations by shallow whole genome sequencing points to EFNA5, BAHD1 and PPP2R5E as novel candidates for genes causing human Mendelian disorders', 2019, 22, 140);
INSERT INTO prace VALUES (159, 'Credibility of Evolutionary Events in Gene Trees', 2019, 2, 70);
INSERT INTO prace VALUES (160, 'Mathematical properties of the gene duplication cost', 2019, 4, 70);
INSERT INTO prace VALUES (161, 'Feasibility Algorithms for the Duplication-Loss Cost', 2019, 3, 140);
INSERT INTO prace VALUES (162, 'High-Throughput BCR Sequencing and Single-Cell Transcriptomics Reveal Distinct Transcriptional Profiles Associated with Subclonal Evolution of Follicular Lymphoma', 2019, 13, 200);
INSERT INTO prace VALUES (163, 'Continuous Reachability for Unordered Data Petri Nets is in PTime', 2019, 4, 140);
INSERT INTO prace VALUES (164, '30 Sensors to Mars: Toward Distributed Support Systems for Astronauts in Space Habitats', 2019, 7, 140);
INSERT INTO prace VALUES (165, 'GRUNGE: A Grand Unified ATP Challenge', 2019, 5, 140);
INSERT INTO prace VALUES (166, 'Declarative Proof Translation', 2019, 2, 140);
INSERT INTO prace VALUES (167, 'Higher-Order Tarski Grothendieck as a Foundation for Formal Proof', 2019, 3, 140);
INSERT INTO prace VALUES (168, 'Reliable Hubs for Partially-Dynamic All-Pairs Shortest Paths in Directed Graphs', 2019, 2, 140);
INSERT INTO prace VALUES (169, 'Min-Cost Flow in Unit-Capacity Planar Graphs', 2019, 2, 140);
INSERT INTO prace VALUES (170, 'Codensity Games for Bisimilarity', 2019, 5, 200);
INSERT INTO prace VALUES (171, 'Scalar and Vectorial $μ$-calculus with Atoms', 2019, 2, 70);
INSERT INTO prace VALUES (172, 'History-Dependent Nominal μ-Calculus', 2019, 2, 200);
INSERT INTO prace VALUES (173, 'Expressiveness of probabilistic modal logics: A gradual approach', 2019, 4, 70);
INSERT INTO prace VALUES (174, 'Definable isomorphism problem', 2019, 5, 70);
INSERT INTO prace VALUES (175, 'Logical properties of random graphs from small addable classes', 2019, 2, 70);
INSERT INTO prace VALUES (176, 'Fine-Grained Complexity of k-OPT in Bounded-Degree Graphs for Solving TSP', 2019, 4, 140);
INSERT INTO prace VALUES (177, 'Tight Lower Bounds for the Complexity of Multicoloring', 2019, 5, 70);
INSERT INTO prace VALUES (178, 'Rare Siblings Speed-Up Deterministic Detection and Counting of Small Pattern Graphs', 2019, 2, 140);
INSERT INTO prace VALUES (179, 'A fast deterministic detection of small pattern graphs in graphs without large cliques', 2019, 2, 100);
INSERT INTO prace VALUES (180, 'Structure and function of the Ts2631 endolysin of Thermus scotoductus phage vB\_Tsc2631 with unique N-terminal extension used for peptidoglycan binding', 2019, 7, 140);
INSERT INTO prace VALUES (181, 'Enumerating Connected Subgraphs and Computing the Myerson and Shapley Values in Graph-restricted Games', 2019, 4, 140);
INSERT INTO prace VALUES (182, 'Attachment Centrality: Measure for Connectivity in Networks', 2019, 4, 200);
INSERT INTO prace VALUES (183, 'Strategic Attack & Defense in Security Diffusion Games', 2019, 3, 140);
INSERT INTO prace VALUES (184, 'Attacking Similarity-Based Link Prediction in Social Networks', 2019, 5, 200);
INSERT INTO prace VALUES (185, 'A Measure of Added Value in Groups', 2019, 5, 100);
INSERT INTO prace VALUES (186, 'How to Hide one’s Relationships from Link prediction Algorithms', 2019, 6, 140);
INSERT INTO prace VALUES (187, 'Adversarial Robustness of Similarity-Based Link Prediction', 2019, 3, 200);
INSERT INTO prace VALUES (188, 'A Subquadratic Approximation Scheme for Partition', 2019, 3, 200);
INSERT INTO prace VALUES (189, 'Equal-subset-sum faster than the meet-in-the-middle', 2019, 4, 140);
INSERT INTO prace VALUES (190, 'On the semantics of Cypher''s implicit group-by', 2019, 3, 70);
INSERT INTO prace VALUES (191, 'On Finite and Unrestricted Query Entailment beyond SQ with Number Restrictions on Transitive Roles', 2019, 5, 200);
INSERT INTO prace VALUES (192, 'Credibility of Evolutionary Events in Gene Trees', 2019, 2, 70);
INSERT INTO prace VALUES (193, 'The Influence of the Test Operator on the Expressive Power of PDL-like Logics', 2019, 1, 100);
INSERT INTO prace VALUES (194, 'Bisimilarity in Fuzzy Description Logics Under the Zadeh Semantics', 2019, 1, 200);
INSERT INTO prace VALUES (195, 'Minimizing interpretations in fuzzy description logics under the Gödel semantics by using fuzzy bisimulations', 2019, 2, 70);
INSERT INTO prace VALUES (196, 'An expressive and tractable rule-based description language', 2019, 2, 100);
INSERT INTO prace VALUES (197, 'Bisimulations for Fuzzy Description Logics with Involutive Negation Under the Gödel Semantics', 2019, 2, 20);
INSERT INTO prace VALUES (198, 'Incorporating Stratified Negation into Query-Subquery Nets for Evaluating Queries to Stratified Deductive Databases', 2019, 2, 20);
INSERT INTO prace VALUES (199, 'PyLink: a PyMOL plugin to identify links', 2019, 5, 200);
INSERT INTO prace VALUES (200, 'Defining and detecting links in chromosomes', 2019, 3, 140);
INSERT INTO prace VALUES (201, 'Parity Games: Zielonka''s Algorithm in Quasi-Polynomial Time', 2019, 1, 140);
INSERT INTO prace VALUES (202, 'Extensions of the Caucal Hierarchy?', 2019, 1, 20);
INSERT INTO prace VALUES (203, 'Inferring duplication episodes from unrooted gene trees', 2019, 2, 140);
INSERT INTO prace VALUES (204, 'Efficient algorithms for genomic duplication models', 2019, 2, 70);
INSERT INTO prace VALUES (205, 'The Worst Balanced Partially Ordered Sets—Ladders with Broken Rungs', 2019, 1, 100);
INSERT INTO prace VALUES (206, 'Finding Hamiltonian Cycle in Graphs of Bounded Treewidth: Experimental Evaluation', 2019, 2, 100);
INSERT INTO prace VALUES (207, 'Deleting Vertices to Graphs of Bounded Genus', 2019, 2, 70);
INSERT INTO prace VALUES (208, 'An Exponential Lower Bound for Cut Sparsifiers in Planar Graphs', 2019, 3, 70);
INSERT INTO prace VALUES (209, 'Polynomial-time algorithm for Maximum Weight Independent Set on P6-free graphs', 2019, 4, 200);
INSERT INTO prace VALUES (210, 'Turing Kernelization for Finding Long Paths in Graph Classes Excluding a Topological Minor', 2019, 3, 70);
INSERT INTO prace VALUES (211, 'Empirical Evaluation of Approximation Algorithms for Generalized Graph Coloring and Uniform Quasi-wideness', 2019, 5, 100);
INSERT INTO prace VALUES (212, 'Subexponential-Time Algorithms for Maximum Independent Set in P_t-Free and Broom-Free Graphs', 2019, 6, 70);
INSERT INTO prace VALUES (213, 'A Deterministic Polynomial Kernel for Odd Cycle Transversal and Vertex Multiway Cut in Planar Graphs', 2019, 3, 140);
INSERT INTO prace VALUES (214, 'Efficient Approximation Schemes for Uniform-Cost Clustering Problems in Planar Graphs', 2019, 3, 140);
INSERT INTO prace VALUES (215, 'Packing Directed Circuits Quarter-Integrally', 2019, 5, 140);
INSERT INTO prace VALUES (216, 'A Polynomial-Time Approximation Scheme for Facility Location on Planar Graphs', 2019, 3, 200);
INSERT INTO prace VALUES (217, 'Polynomial bounds for centered colorings on proper minor-closed graph classes', 2019, 2, 200);
INSERT INTO prace VALUES (218, 'Subexponential-Time Algorithms for Finding Large Induced Sparse Subgraphs', 2019, 6, 70);
INSERT INTO prace VALUES (219, 'Integer Programming and Incidence Treedepth', 2019, 6, 140);
INSERT INTO prace VALUES (220, 'Reachability for Bounded Branching VASS', 2019, 2, 140);
INSERT INTO prace VALUES (221, 'On width measures and topological problems on semi-complete digraphs', 2019, 2, 140);
INSERT INTO prace VALUES (222, 'On Geometric Set Cover for Orthants', 2019, 4, 140);
INSERT INTO prace VALUES (223, 'Tight Complexity Lower Bounds for Integer Linear Programming with Few Constraints', 2019, 3, 140);
INSERT INTO prace VALUES (224, 'A note on the complexity of a phaseless polynomial interpolation', 2019, 2, 100);
INSERT INTO prace VALUES (225, 'Efficient Representation and Counting of Antipower Factors in Words', 2019, 6, 20);
INSERT INTO prace VALUES (226, 'Quasi-Linear-Time Algorithm for Longest Common Circular Factor', 2019, 9, 70);
INSERT INTO prace VALUES (227, 'Circular Pattern Matching with k Mismatches', 2019, 8, 140);
INSERT INTO prace VALUES (228, 'Weighted Shortest Common Supersequence Problem Revisited', 2019, 8, 70);
INSERT INTO prace VALUES (229, 'On-line weighted pattern matching', 2019, 4, 70);
INSERT INTO prace VALUES (230, 'Longest Common Substring with Approximately k Mismatches', 2019, 3, 70);
INSERT INTO prace VALUES (231, 'Quasi-Periodicity in Streams', 2019, 3, 70);
INSERT INTO prace VALUES (232, 'Pattern Matching and Consensus Problems on Weighted Sequences and Profiles', 2019, 3, 40);
INSERT INTO prace VALUES (233, 'Longest Common Substring Made Fully Dynamic', 2019, 4, 140);
INSERT INTO prace VALUES (234, 'Internal Dictionary Matching', 2019, 6, 140);
INSERT INTO prace VALUES (235, 'Syntactic View of Sigma-Tau Generation of Permutations', 2019, 2, 20);
INSERT INTO prace VALUES (236, 'Optimizing Egalitarian Performance when Colocating Tasks with Types for Cloud Data Center Resource Management', 2019, 2, 140);
INSERT INTO prace VALUES (237, '(1 + \(ε\))-Approximate Incremental Matching in Constant Deterministic Amortized Time', 2019, 5, 200);
INSERT INTO prace VALUES (238, 'Fair Knapsack', 2019, 2, 200);
INSERT INTO prace VALUES (239, 'A Quantitative Analysis of Multi-Winner Rules', 2019, 2, 200);
INSERT INTO prace VALUES (240, 'Approval-Based Elections and Distortion of Voting Rules', 2019, 2, 200);
INSERT INTO prace VALUES (241, 'Committee Scoring Rules: Axiomatic Characterization and Hierarchy', 2019, 4, 70);
INSERT INTO prace VALUES (242, 'Axiomatic characterization of committee scoring rules', 2019, 3, 200);
INSERT INTO prace VALUES (243, 'Proportional Representation in Elections: STV vs PAV', 2019, 4, 200);
INSERT INTO prace VALUES (244, 'Matchings under Preferences: Strength of Stability and Trade-Offs', 2019, 3, 200);
INSERT INTO prace VALUES (245, 'How Similar Are Two Elections?', 2019, 5, 200);
INSERT INTO prace VALUES (246, 'Uniformisation Gives the Full Strength of Regular Languages', 2019, 3, 140);
INSERT INTO prace VALUES (247, 'The logical strength of B\üchi''s decidability theorem', 2019, 4, 70);
INSERT INTO prace VALUES (248, 'Multivariate Ovulation Window Detection at OvuFriend', 2019, 10, 20);
INSERT INTO prace VALUES (249, 'On Boolean Representation of Continuous Data Biclustering', 2019, 2, 70);
INSERT INTO prace VALUES (250, 'On resilient feature selection: Computational foundations of r-C-reducts', 2019, 2, 200);
INSERT INTO prace VALUES (251, 'Paraconsistent Reasoning in Cops and Robber Game with Uncertain Information: A Simulation-Based Analysis', 2019, 3, 40);
INSERT INTO prace VALUES (252, 'Decision-Making Support Using Nonmonotonic Probabilistic Reasoning', 2019, 1, 20);
INSERT INTO prace VALUES (253, 'Learning signaling networks from combinatorial perturbations by exploiting siRNA off-target effects', 2019, 2, 200);
INSERT INTO prace VALUES (254, 'ARA: accurate, reliable and active histopathological image classification framework with Bayesian deep learning', 2019, 4, 140);
INSERT INTO prace VALUES (255, 'QChromosomeVisualizer: A new tool for 3D visualization of long simulations of polymer-like chromosome models', 2019, 3, 100);
INSERT INTO prace VALUES (256, 'Random Walk Decay Centrality', 2019, 3, 200);
INSERT INTO prace VALUES (257, 'Approximating APSP without Scaling: Equivalence of Approximate Min-plus and Exact Min-Max', 2019, 3, 200);
INSERT INTO prace VALUES (258, 'BPscore: an effective metric for meaningful comparisons of structural chromosome segmentations', 2019, 2, 70);
INSERT INTO prace VALUES (259, 'Clifford Algebras Meet Tree Decompositions', 2019, 1, 70);
INSERT INTO prace VALUES (260, 'Losing Treewidth by Separating Subsets', 2019, 5, 200);
INSERT INTO prace VALUES (261, 'Constant-Factor FPT Approximation for Capacitated k-Median', 2019, 5, 140);
INSERT INTO prace VALUES (262, 'Lessons from Communication Problems that Nearly Jeopardized Development of Hardware-Software Support for a 1000-Device IoT Testbed', 2020, 15, 140);
INSERT INTO prace VALUES (263, 'ImaGINator: Conditional Spatio-Temporal GAN for Video Generation', 2020, 4, 140);
INSERT INTO prace VALUES (264, 'G3AN: Disentangling motion and appearance for video generation', 2020, 4, 200);
INSERT INTO prace VALUES (265, 'Extensions of ω-Regular Languages', 2020, 4, 200);
INSERT INTO prace VALUES (266, 'First-order tree-to-tree functions', 2020, 2, 200);
INSERT INTO prace VALUES (267, 'Single-Use Automata and Transducers for Infinite Alphabets', 2020, 2, 140);
INSERT INTO prace VALUES (268, 'Some Remarks on Deciding Equivalence for Graph-To-Graph Transducers', 2020, 2, 140);
INSERT INTO prace VALUES (269, 'Undecidability of a weak version of MSO+U', 2020, 5, 70);
INSERT INTO prace VALUES (270, 'From Gap-Exponential Time Hypothesis to Fixed Parameter Tractable Inapproximability: Clique, Dominating Set, and More', 2020, 7, 200);
INSERT INTO prace VALUES (271, 'Lower Bounds for the Parameterized Complexity of Minimum Fill-in and Other Completion Problems', 2020, 5, 140);
INSERT INTO prace VALUES (272, 'An Approach to Regular Separability in Vector Addition Systems', 2020, 2, 200);
INSERT INTO prace VALUES (273, 'Reachability in Fixed Dimension Vector Addition Systems with States', 2020, 5, 140);
INSERT INTO prace VALUES (274, 'Universality Problem for Unambiguous VASS', 2020, 3, 140);
INSERT INTO prace VALUES (275, 'Getting insight into the pan-genome structure with PangTree', 2020, 2, 140);
INSERT INTO prace VALUES (276, 'Dimensionality Reduction for k-Distance Applied to Persistent Homology', 2020, 4, 140);
INSERT INTO prace VALUES (277, 'A game of hide and seek in networks', 2020, 3, 200);
INSERT INTO prace VALUES (278, 'The strategy of conquest', 2020, 3, 200);
INSERT INTO prace VALUES (279, 'A PTAS for Euclidean TSP with Hyperplane Neighborhoods', 2020, 4, 140);
INSERT INTO prace VALUES (280, 'Drawing graphs on few lines and few planes', 2020, 6, 20);
INSERT INTO prace VALUES (281, 'Low Entropy Sub-Networks Prevent the Integration of Metabolomic and Transcriptomic Data', 2020, 3, 100);
INSERT INTO prace VALUES (282, 'Masserstein: Linear regression of mass spectra by optimal transport', 2020, 7, 70);
INSERT INTO prace VALUES (283, 'Knot_pull—python package for biopolymer smoothing and knot detection', 2020, 3, 200);
INSERT INTO prace VALUES (284, 'Breakpoint mapping of symptomatic balanced translocations links the EPHA6, KLF13 and UBR3 genes to novel disease phenotype', 2020, 20, 140);
INSERT INTO prace VALUES (285, 'New Hybrid Quantum Annealing Algorithms for Solving Vehicle Routing Problem', 2020, 9, 140);
INSERT INTO prace VALUES (286, 'Exact median-tree inference for unrooted reconciliation costs', 2020, 3, 100);
INSERT INTO prace VALUES (287, 'Minimizing genomic duplication episodes', 2020, 3, 70);
INSERT INTO prace VALUES (288, 'Parametrized Universality Problems for One-Counter Nets', 2020, 4, 140);
INSERT INTO prace VALUES (289, 'Human Nature: The Subject and the Headache of IoT-Based Sociometric Studies', 2020, 5, 140);
INSERT INTO prace VALUES (290, 'On Positive-Correlation-Promoting Reducts', 2020, 4, 20);
INSERT INTO prace VALUES (291, 'Single-Source Shortest Paths and Strong Connectivity in Dynamic Planar Graphs', 2020, 2, 140);
INSERT INTO prace VALUES (292, 'Bisimulational categoricity', 2020, 1, 140);
INSERT INTO prace VALUES (293, 'Many Visits TSP Revisited', 2020, 5, 140);
INSERT INTO prace VALUES (294, 'The Asymmetric Travelling Salesman Problem In Sparse Digraphs', 2020, 2, 70);
INSERT INTO prace VALUES (295, 'The PACE 2020 Parameterized Algorithms and Computational Experiments Challenge: Treedepth', 2020, 6, 70);
INSERT INTO prace VALUES (296, 'A simple approach to nondecreasing paths', 2020, 2, 70);
INSERT INTO prace VALUES (297, 'A High-Throughput Screen for Transcription Activation Domains Reveals Their Sequence Features and Permits Prediction by Deep Learning', 2020, 9, 200);
INSERT INTO prace VALUES (298, 'WQO dichotomy for 3-graph', 2020, 2, 70);
INSERT INTO prace VALUES (299, 'Petri net–based model of the human DNA base excision repair pathway', 2020, 5, 100);
INSERT INTO prace VALUES (300, 'Fair division in the presence of externalities', 2020, 2, 70);
INSERT INTO prace VALUES (301, 'Deep Learning Versus Traditional Solutions for Group Trajectory Outliers', 2020, 5, 200);
INSERT INTO prace VALUES (302, 'Hiding in Multilayer Networks', 2020, 3, 200);
INSERT INTO prace VALUES (303, 'Partition decision trees: representation for efficient computation of the Shapley value extended to games with externalities', 2020, 5, 70);
INSERT INTO prace VALUES (304, 'Signed Graph Games: Coalitional Games with Friends, Enemies and Allies', 2020, 5, 200);
INSERT INTO prace VALUES (305, 'The Manipulability of Centrality Measures-An Axiomatic Approach', 2020, 4, 200);
INSERT INTO prace VALUES (306, 'Improved approximation for Fractionally Subadditive Network Design', 2020, 2, 70);
INSERT INTO prace VALUES (307, 'On Finite Entailment of Non-Local Queries in Description Logics', 2020, 5, 200);
INSERT INTO prace VALUES (308, 'Ontology Focusing: Knowledge-Enriched Databases on Demand', 2020, 6, 140);
INSERT INTO prace VALUES (309, 'Bisimulation and bisimilarity for fuzzy description logics under the Gödel semantics', 2020, 5, 140);
INSERT INTO prace VALUES (310, 'ExpTime Tableaux with Global Caching for Hybrid PDL', 2020, 1, 140);
INSERT INTO prace VALUES (311, 'GLN: a method to reveal unique properties of lasso type topology in proteins', 2020, 3, 140);
INSERT INTO prace VALUES (312, 'Topoly: Python package to analyze topology of polymers', 2020, 5, 140);
INSERT INTO prace VALUES (313, 'Computing Measures of Weak-MSO Definable Sets of Trees', 2020, 3, 140);
INSERT INTO prace VALUES (314, 'A Quasi-Polynomial Black-Box Algorithm for Fixed Point Evaluation', 2020, 3, 70);
INSERT INTO prace VALUES (315, 'A Type System Describing Unboundedness', 2020, 1, 70);
INSERT INTO prace VALUES (316, 'Bisimulation Finiteness of Pushdown Systems Is Elementary', 2020, 2, 200);
INSERT INTO prace VALUES (317, 'Cost Automata, Safe Schemes, and Downward Closures', 2020, 4, 140);
INSERT INTO prace VALUES (318, 'Higher-Order Nonemptiness Step by Step', 2020, 1, 70);
INSERT INTO prace VALUES (319, 'On the Expressive Power of Higher-Order Pushdown Systems', 2020, 1, 70);
INSERT INTO prace VALUES (320, 'Parity Games: Another View on Lehtinen''s Algorithm', 2020, 1, 70);
INSERT INTO prace VALUES (321, 'Recursion Schemes, the MSO Logic, and the U quantifier', 2020, 1, 70);
INSERT INTO prace VALUES (322, 'A Double Exponential Lower Bound for the Distinct Vectors Problem', 2020, 2, 70);
INSERT INTO prace VALUES (323, 'The Complexity of Connectivity Problems in Forbidden-Transition Graphs And Edge-Colored Graphs', 2020, 5, 140);
INSERT INTO prace VALUES (324, 'An Improved FPT Algorithm for Independent Feedback Vertex Set', 2020, 2, 40);
INSERT INTO prace VALUES (325, 'On the Maximum Weight Independent Set Problem in Graphs without Induced Cycles of Length at Least Five', 2020, 4, 100);
INSERT INTO prace VALUES (326, 'Quasi-polynomial time approximation schemes for the Maximum Weight Independent Set Problem in H-free graphs', 2020, 4, 200);
INSERT INTO prace VALUES (327, 'Two lower bounds for p-centered colorings', 2020, 5, 70);
INSERT INTO prace VALUES (328, 'Hamiltonian Cycle Parameterized by Treedepth in Single Exponential Time and Polynomial Space', 2020, 4, 140);
INSERT INTO prace VALUES (329, 'Shorter Labeling Schemes for Planar Graphs', 2020, 3, 200);
INSERT INTO prace VALUES (330, 'VC Density of Set Systems Definable in Tree-Like Graphs', 2020, 2, 140);
INSERT INTO prace VALUES (331, 'An exponential time parameterized algorithm for planar disjoint paths', 2020, 5, 200);
INSERT INTO prace VALUES (332, 'Clustering Powers of Sparse Graphs', 2020, 4, 100);
INSERT INTO prace VALUES (333, 'Enumerating Minimal Dominating Sets in Kt-free Graphs and Variants', 2020, 5, 140);
INSERT INTO prace VALUES (334, 'Finding Large H-Colorable Subgraphs in Hereditary Graph Classes', 2020, 5, 140);
INSERT INTO prace VALUES (335, 'First-Order Interpretations of Bounded Expansion Classes', 2020, 7, 100);
INSERT INTO prace VALUES (336, 'Model-Checking on Ordered Structures', 2020, 9, 100);
INSERT INTO prace VALUES (337, 'On Polynomial Recursive Sequences', 2020, 5, 140);
INSERT INTO prace VALUES (338, 'On low rank-width colorings', 2020, 3, 100);
INSERT INTO prace VALUES (339, 'Quasi-Polynomial Time Approximation Schemes for Packing and Covering Problems in Planar Graphs', 2020, 3, 70);
INSERT INTO prace VALUES (340, 'Tight Complexity Lower Bounds for Integer Linear Programming with Few Constraints', 2020, 3, 70);
INSERT INTO prace VALUES (341, 'A Linear-Time Algorithm for Seeds Computation', 2020, 5, 140);
INSERT INTO prace VALUES (342, 'Approximating Longest Common Substring with k mismatches: Theory and Practice', 2020, 4, 70);
INSERT INTO prace VALUES (343, 'Counting Distinct Patterns in Internal Dictionary Matching', 2020, 8, 70);
INSERT INTO prace VALUES (344, 'Dynamic and Internal Longest Common Substring', 2020, 4, 70);
INSERT INTO prace VALUES (345, 'Efficient Computation of 2-Covers of a String', 2020, 2, 140);
INSERT INTO prace VALUES (346, 'Efficient Enumeration of Distinct Factors Using Package Representations', 2020, 5, 70);
INSERT INTO prace VALUES (347, 'Faster algorithms for 1-mappability of a sequence', 2020, 6, 100);
INSERT INTO prace VALUES (348, 'Indexing weighted sequences: Neat and efficient', 2020, 5, 70);
INSERT INTO prace VALUES (349, 'Internal Quasiperiod Queries', 2020, 7, 70);
INSERT INTO prace VALUES (350, 'Shortest Covers of All Cyclic Shifts of a String', 2020, 7, 20);
INSERT INTO prace VALUES (351, 'Streaming k-mismatch with error correcting and applications', 2020, 2, 70);
INSERT INTO prace VALUES (352, 'String periods in the order-preserving model', 2020, 6, 70);
INSERT INTO prace VALUES (353, 'The Number of Repetitions in 2D-Strings', 2020, 6, 140);
INSERT INTO prace VALUES (354, 'Unary Words Have the Smallest Levenshtein k-Neighbourhoods', 2020, 5, 70);
INSERT INTO prace VALUES (355, 'Universal reconstruction of a string', 2020, 5, 100);
INSERT INTO prace VALUES (356, 'k-Approximate Quasiperiodicity under Hamming and Edit Distance', 2020, 2, 70);
INSERT INTO prace VALUES (357, 'Autopilot: workload autoscaling at Google', 2020, 11, 140);
INSERT INTO prace VALUES (358, 'Scheduling Methods to Reduce Response Latency of Function as a Service', 2020, 2, 70);
INSERT INTO prace VALUES (359, 'Derived Hall algebras of one-cycle gentle algebras: The infinite global dimension case', 2020, 2, 100);
INSERT INTO prace VALUES (360, 'Complexity of Computing the Shapley Value in Games with Externalities', 2020, 1, 200);
INSERT INTO prace VALUES (361, 'Comparing election methods where each voter ranks only few candidates', 2020, 2, 200);
INSERT INTO prace VALUES (362, 'A characterization of the single-peaked single-crossing domain', 2020, 3, 70);
INSERT INTO prace VALUES (363, 'Drawing a map of elections in the space of statistical cultures', 2020, 5, 200);
INSERT INTO prace VALUES (364, 'Evaluating committees for representative democracies: The distortion and beyond', 2020, 2, 200);
INSERT INTO prace VALUES (365, 'Mixed integer programming with convex/concave constraints: Fixed-parameter tractability and applications to multicovering and voting', 2020, 5, 100);
INSERT INTO prace VALUES (366, 'Price of fairness in budget division and probabilistic social choice', 2020, 3, 200);
INSERT INTO prace VALUES (367, 'Proportionality and the Limits of Welfarism', 2020, 2, 200);
INSERT INTO prace VALUES (368, 'Utilitarian welfare and representation guarantees of approval-based multiwinner rules', 2020, 2, 200);
INSERT INTO prace VALUES (369, 'On the Succinctness of Alternating Parity Good-For-Games Automata', 2020, 4, 70);
INSERT INTO prace VALUES (370, 'Regular Choice Functions and Uniformisations For countable Domains', 2020, 2, 140);
INSERT INTO prace VALUES (371, 'Uniformisations of Regular Relations Over Bi-Infinite Words', 2020, 3, 200);
INSERT INTO prace VALUES (372, 'Research on Heuristic Optimization and Operations in IoT', 2020, 4, 40);
INSERT INTO prace VALUES (373, 'Approximate Decision Tree Induction over Approximately Engineered Data Features', 2020, 2, 20);
INSERT INTO prace VALUES (374, 'From Big Data to business analytics: The case study of churn prediction', 2020, 4, 200);
INSERT INTO prace VALUES (375, 'Heuristic Search of Exact Biclusters in Binary Data', 2020, 3, 100);
INSERT INTO prace VALUES (376, 'Rough-set-driven approach for attribute reduction in fuzzy formal concept analysis', 2020, 4, 140);
INSERT INTO prace VALUES (377, 'The Problem of Finding the Simplest Classifier Ensemble is NP-Hard – A Rough-Set-Inspired Formulation Based on Decision Bireducts', 2020, 2, 20);
INSERT INTO prace VALUES (378, 'IsoSpec2: Ultrafast Fine Structure Calculator', 2020, 3, 140);
INSERT INTO prace VALUES (379, 'Algorithmic Discovery of Tactical Combinations for Advanced Organic Syntheses', 2020, 7, 200);
INSERT INTO prace VALUES (380, 'A Paraconsistent ASP-like Language with Tractable Model Generation', 2020, 1, 20);
INSERT INTO prace VALUES (381, 'On the Probability and Cost of Ignorance, Inconsistency, Nonsense and More', 2020, 1, 40);
INSERT INTO prace VALUES (382, 'Rough Forgetting', 2020, 2, 20);
INSERT INTO prace VALUES (383, 'A mathematical model of the metastatic bottleneck predicts patient outcome and response to cancer treatment', 2020, 4, 140);
INSERT INTO prace VALUES (384, 'Eleven grand challenges in single-cell data science', 2020, 52, 200);
INSERT INTO prace VALUES (385, 'Feature selection strategies for drug sensitivity prediction', 2020, 8, 140);
INSERT INTO prace VALUES (386, 'The Unconstrained Diameters of the Duplication-Loss Cost and the Loss Cost', 2020, 3, 70);
INSERT INTO prace VALUES (387, 'Aggregate Queries on Sparse Databases', 2020, 1, 200);
INSERT INTO prace VALUES (388, 'Register Automata with Extrema Constraints, and an Application to Two-Variable Logic', 2020, 2, 200);
INSERT INTO prace VALUES (389, 'Automated inference of gene regulatory networks using explicit regulatory modules', 2020, 2, 70);


CREATE TABLE autorstwo (
	Praca INTEGER NOT NULL,
	Autor TEXT NOT NULL
);


INSERT INTO autorstwo VALUES (1, 'Schubert');
INSERT INTO autorstwo VALUES (2, 'Clemente');
INSERT INTO autorstwo VALUES (2, 'Czerwiński');
INSERT INTO autorstwo VALUES (2, 'Lasota');
INSERT INTO autorstwo VALUES (3, 'Clemente');
INSERT INTO autorstwo VALUES (3, 'Czerwiński');
INSERT INTO autorstwo VALUES (3, 'Lasota');
INSERT INTO autorstwo VALUES (4, 'Clemente');
INSERT INTO autorstwo VALUES (4, 'Lasota');
INSERT INTO autorstwo VALUES (5, 'Czerwiński');
INSERT INTO autorstwo VALUES (5, 'Lasota');
INSERT INTO autorstwo VALUES (6, 'Dunin-Kęplicz');
INSERT INTO autorstwo VALUES (6, 'Szałas');
INSERT INTO autorstwo VALUES (7, 'Dunin-Kęplicz');
INSERT INTO autorstwo VALUES (7, 'Szałas');
INSERT INTO autorstwo VALUES (8, 'Dziubiński');
INSERT INTO autorstwo VALUES (9, 'Górecki');
INSERT INTO autorstwo VALUES (10, 'Górecki');
INSERT INTO autorstwo VALUES (10, 'Paszek');
INSERT INTO autorstwo VALUES (11, 'Hofman');
INSERT INTO autorstwo VALUES (12, 'Hofman');
INSERT INTO autorstwo VALUES (13, 'Hofman');
INSERT INTO autorstwo VALUES (14, 'Janusz');
INSERT INTO autorstwo VALUES (14, 'Ślęzak');
INSERT INTO autorstwo VALUES (15, 'Karczmarz');
INSERT INTO autorstwo VALUES (15, 'Sankowski');
INSERT INTO autorstwo VALUES (16, 'Karczmarz');
INSERT INTO autorstwo VALUES (16, 'Sankowski');
INSERT INTO autorstwo VALUES (17, 'Klin');
INSERT INTO autorstwo VALUES (18, 'Klin');
INSERT INTO autorstwo VALUES (19, 'Klin');
INSERT INTO autorstwo VALUES (20, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (20, 'Radoszewski');
INSERT INTO autorstwo VALUES (20, 'Rytter');
INSERT INTO autorstwo VALUES (20, 'Waleń');
INSERT INTO autorstwo VALUES (21, 'Kopczyński');
INSERT INTO autorstwo VALUES (21, 'Toruńczyk');
INSERT INTO autorstwo VALUES (22, 'Kopczyński');
INSERT INTO autorstwo VALUES (23, 'Celińska-Kopczyńska');
INSERT INTO autorstwo VALUES (23, 'Kopczyński');
INSERT INTO autorstwo VALUES (24, 'Cygan');
INSERT INTO autorstwo VALUES (24, 'Kowalik');
INSERT INTO autorstwo VALUES (25, 'Cygan');
INSERT INTO autorstwo VALUES (25, 'Kowalik');
INSERT INTO autorstwo VALUES (26, 'Kowalik');
INSERT INTO autorstwo VALUES (26, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (26, 'Wrochna');
INSERT INTO autorstwo VALUES (27, 'Kowaluk');
INSERT INTO autorstwo VALUES (28, 'Michalak');
INSERT INTO autorstwo VALUES (28, 'Skibski');
INSERT INTO autorstwo VALUES (29, 'Michalak');
INSERT INTO autorstwo VALUES (30, 'Michalak');
INSERT INTO autorstwo VALUES (31, 'Michalak');
INSERT INTO autorstwo VALUES (32, 'Mucha');
INSERT INTO autorstwo VALUES (33, 'Cygan');
INSERT INTO autorstwo VALUES (33, 'Mucha');
INSERT INTO autorstwo VALUES (33, 'Węgrzycki');
INSERT INTO autorstwo VALUES (33, 'Włodarczyk');
INSERT INTO autorstwo VALUES (34, 'Nguyen AL');
INSERT INTO autorstwo VALUES (35, 'Pacuk');
INSERT INTO autorstwo VALUES (35, 'Sankowski');
INSERT INTO autorstwo VALUES (35, 'Węgrzycki');
INSERT INTO autorstwo VALUES (35, 'Wygocki');
INSERT INTO autorstwo VALUES (36, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (37, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (37, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (37, 'Wrochna');
INSERT INTO autorstwo VALUES (38, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (39, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (40, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (41, 'Bojańczyk');
INSERT INTO autorstwo VALUES (41, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (42, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (42, 'Wrochna');
INSERT INTO autorstwo VALUES (43, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (43, 'Wrochna');
INSERT INTO autorstwo VALUES (44, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (44, 'Wrochna');
INSERT INTO autorstwo VALUES (45, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (46, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (47, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (48, 'Radoszewski');
INSERT INTO autorstwo VALUES (49, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (49, 'Radoszewski');
INSERT INTO autorstwo VALUES (50, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (50, 'Radoszewski');
INSERT INTO autorstwo VALUES (51, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (51, 'Radoszewski');
INSERT INTO autorstwo VALUES (52, 'Rządca');
INSERT INTO autorstwo VALUES (53, 'Sankowski');
INSERT INTO autorstwo VALUES (54, 'Sankowski');
INSERT INTO autorstwo VALUES (54, 'Węgrzycki');
INSERT INTO autorstwo VALUES (55, 'Sankowski');
INSERT INTO autorstwo VALUES (55, 'Wygocki');
INSERT INTO autorstwo VALUES (56, 'Schubert');
INSERT INTO autorstwo VALUES (57, 'Skibski');
INSERT INTO autorstwo VALUES (58, 'Skrzypczak');
INSERT INTO autorstwo VALUES (59, 'Michalewski');
INSERT INTO autorstwo VALUES (59, 'Skrzypczak');
INSERT INTO autorstwo VALUES (60, 'Ślęzak');
INSERT INTO autorstwo VALUES (61, 'Adamczyk');
INSERT INTO autorstwo VALUES (61, 'Włodarczyk');
INSERT INTO autorstwo VALUES (62, 'Clemente');
INSERT INTO autorstwo VALUES (62, 'Lasota');
INSERT INTO autorstwo VALUES (63, 'Cygan');
INSERT INTO autorstwo VALUES (63, 'Mucha');
INSERT INTO autorstwo VALUES (63, 'Sankowski');
INSERT INTO autorstwo VALUES (64, 'Czerwiński');
INSERT INTO autorstwo VALUES (64, 'Parys');
INSERT INTO autorstwo VALUES (65, 'Czerwiński');
INSERT INTO autorstwo VALUES (65, 'Hofman');
INSERT INTO autorstwo VALUES (66, 'Czerwiński');
INSERT INTO autorstwo VALUES (66, 'Lasota');
INSERT INTO autorstwo VALUES (67, 'Dziembowski');
INSERT INTO autorstwo VALUES (68, 'Dziembowski');
INSERT INTO autorstwo VALUES (69, 'Dziubiński');
INSERT INTO autorstwo VALUES (70, 'Gambin');
INSERT INTO autorstwo VALUES (70, 'Niemyska');
INSERT INTO autorstwo VALUES (70, 'Startek');
INSERT INTO autorstwo VALUES (71, 'Górecki');
INSERT INTO autorstwo VALUES (72, 'Hofman');
INSERT INTO autorstwo VALUES (72, 'Lasota');
INSERT INTO autorstwo VALUES (73, 'Iwanicki');
INSERT INTO autorstwo VALUES (74, 'Iwanicki');
INSERT INTO autorstwo VALUES (75, 'Iwanicki');
INSERT INTO autorstwo VALUES (76, 'Iwanicki');
INSERT INTO autorstwo VALUES (77, 'Janusz');
INSERT INTO autorstwo VALUES (77, 'Ślęzak');
INSERT INTO autorstwo VALUES (78, 'Janusz');
INSERT INTO autorstwo VALUES (79, 'Karczmarz');
INSERT INTO autorstwo VALUES (80, 'Karczmarz');
INSERT INTO autorstwo VALUES (80, 'Sankowski');
INSERT INTO autorstwo VALUES (81, 'Karczmarz');
INSERT INTO autorstwo VALUES (82, 'Karczmarz');
INSERT INTO autorstwo VALUES (83, 'Radoszewski');
INSERT INTO autorstwo VALUES (83, 'Rytter');
INSERT INTO autorstwo VALUES (83, 'Waleń');
INSERT INTO autorstwo VALUES (84, 'Radoszewski');
INSERT INTO autorstwo VALUES (84, 'Rytter');
INSERT INTO autorstwo VALUES (84, 'Straszyński');
INSERT INTO autorstwo VALUES (84, 'Waleń');
INSERT INTO autorstwo VALUES (85, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (85, 'Radoszewski');
INSERT INTO autorstwo VALUES (85, 'Rytter');
INSERT INTO autorstwo VALUES (85, 'Waleń');
INSERT INTO autorstwo VALUES (86, 'Radoszewski');
INSERT INTO autorstwo VALUES (86, 'Rytter');
INSERT INTO autorstwo VALUES (86, 'Waleń');
INSERT INTO autorstwo VALUES (87, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (87, 'Radoszewski');
INSERT INTO autorstwo VALUES (87, 'Straszyński');
INSERT INTO autorstwo VALUES (88, 'Kowalik');
INSERT INTO autorstwo VALUES (88, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (88, 'Wrochna');
INSERT INTO autorstwo VALUES (89, 'Lasota');
INSERT INTO autorstwo VALUES (90, 'Michalak');
INSERT INTO autorstwo VALUES (91, 'Gogacz');
INSERT INTO autorstwo VALUES (91, 'Murlak');
INSERT INTO autorstwo VALUES (92, 'Niemyska');
INSERT INTO autorstwo VALUES (93, 'Parys');
INSERT INTO autorstwo VALUES (94, 'Parys');
INSERT INTO autorstwo VALUES (95, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (96, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (96, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (97, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (98, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (99, 'Nadara');
INSERT INTO autorstwo VALUES (99, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (100, 'Gajarsky');
INSERT INTO autorstwo VALUES (100, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (100, 'Toruńczyk');
INSERT INTO autorstwo VALUES (101, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (102, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (102, 'Toruńczyk');
INSERT INTO autorstwo VALUES (103, 'Bojańczyk');
INSERT INTO autorstwo VALUES (103, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (104, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (104, 'Toruńczyk');
INSERT INTO autorstwo VALUES (105, 'Diks');
INSERT INTO autorstwo VALUES (105, 'Rytter');
INSERT INTO autorstwo VALUES (106, 'Rządca');
INSERT INTO autorstwo VALUES (107, 'Rządca');
INSERT INTO autorstwo VALUES (107, 'Skowron');
INSERT INTO autorstwo VALUES (108, 'Schmude');
INSERT INTO autorstwo VALUES (109, 'Skowron');
INSERT INTO autorstwo VALUES (110, 'Skowron');
INSERT INTO autorstwo VALUES (111, 'Skowron');
INSERT INTO autorstwo VALUES (112, 'Skowron');
INSERT INTO autorstwo VALUES (113, 'Skowron');
INSERT INTO autorstwo VALUES (114, 'Skowron');
INSERT INTO autorstwo VALUES (115, 'Skrzypczak');
INSERT INTO autorstwo VALUES (116, 'Skrzypczak');
INSERT INTO autorstwo VALUES (117, 'Janusz');
INSERT INTO autorstwo VALUES (117, 'Ślęzak');
INSERT INTO autorstwo VALUES (118, 'Ślęzak');
INSERT INTO autorstwo VALUES (119, 'Bojańczyk');
INSERT INTO autorstwo VALUES (119, 'Toruńczyk');
INSERT INTO autorstwo VALUES (120, 'Skibski');
INSERT INTO autorstwo VALUES (121, 'Skibski');
INSERT INTO autorstwo VALUES (122, 'Adamczyk');
INSERT INTO autorstwo VALUES (122, 'Włodarczyk');
INSERT INTO autorstwo VALUES (123, 'Biliński');
INSERT INTO autorstwo VALUES (124, 'Bojańczyk');
INSERT INTO autorstwo VALUES (124, 'Lhote');
INSERT INTO autorstwo VALUES (125, 'Bojańczyk');
INSERT INTO autorstwo VALUES (125, 'Klin');
INSERT INTO autorstwo VALUES (126, 'Bojańczyk');
INSERT INTO autorstwo VALUES (126, 'Skrzypczak');
INSERT INTO autorstwo VALUES (127, 'Bojańczyk');
INSERT INTO autorstwo VALUES (127, 'Kelmendi');
INSERT INTO autorstwo VALUES (127, 'Skrzypczak');
INSERT INTO autorstwo VALUES (128, 'Celińska-Kopczyńska');
INSERT INTO autorstwo VALUES (129, 'Clemente');
INSERT INTO autorstwo VALUES (129, 'Hofman');
INSERT INTO autorstwo VALUES (130, 'Clemente');
INSERT INTO autorstwo VALUES (131, 'Clemente');
INSERT INTO autorstwo VALUES (131, 'Lasota');
INSERT INTO autorstwo VALUES (132, 'Cygan');
INSERT INTO autorstwo VALUES (132, 'Mucha');
INSERT INTO autorstwo VALUES (132, 'Węgrzycki');
INSERT INTO autorstwo VALUES (132, 'Włodarczyk');
INSERT INTO autorstwo VALUES (133, 'Cygan');
INSERT INTO autorstwo VALUES (133, 'Kowalik');
INSERT INTO autorstwo VALUES (134, 'Cygan');
INSERT INTO autorstwo VALUES (134, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (134, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (135, 'Cygan');
INSERT INTO autorstwo VALUES (135, 'Mucha');
INSERT INTO autorstwo VALUES (136, 'Czerwiński');
INSERT INTO autorstwo VALUES (136, 'Hofman');
INSERT INTO autorstwo VALUES (136, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (137, 'Czerwiński');
INSERT INTO autorstwo VALUES (137, 'Lasota');
INSERT INTO autorstwo VALUES (138, 'Czerwiński');
INSERT INTO autorstwo VALUES (138, 'Lasota');
INSERT INTO autorstwo VALUES (139, 'Czerwiński');
INSERT INTO autorstwo VALUES (139, 'Lasota');
INSERT INTO autorstwo VALUES (140, 'Czerwiński');
INSERT INTO autorstwo VALUES (140, 'Nadara');
INSERT INTO autorstwo VALUES (140, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (141, 'Diks');
INSERT INTO autorstwo VALUES (141, 'Rytter');
INSERT INTO autorstwo VALUES (142, 'Dojer');
INSERT INTO autorstwo VALUES (143, 'Dunin-Kęplicz');
INSERT INTO autorstwo VALUES (143, 'Szałas');
INSERT INTO autorstwo VALUES (144, 'Dunin-Kęplicz');
INSERT INTO autorstwo VALUES (144, 'Szałas');
INSERT INTO autorstwo VALUES (145, 'Dunin-Kęplicz');
INSERT INTO autorstwo VALUES (145, 'Szałas');
INSERT INTO autorstwo VALUES (146, 'Dunin-Kęplicz');
INSERT INTO autorstwo VALUES (147, 'Dziembowski');
INSERT INTO autorstwo VALUES (148, 'Dziembowski');
INSERT INTO autorstwo VALUES (149, 'Dziembowski');
INSERT INTO autorstwo VALUES (150, 'Dziembowski');
INSERT INTO autorstwo VALUES (151, 'Fabiański');
INSERT INTO autorstwo VALUES (151, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (151, 'Toruńczyk');
INSERT INTO autorstwo VALUES (152, 'Chung');
INSERT INTO autorstwo VALUES (152, 'Gambin');
INSERT INTO autorstwo VALUES (152, 'Startek');
INSERT INTO autorstwo VALUES (153, 'Gambin');
INSERT INTO autorstwo VALUES (153, 'Jaworski');
INSERT INTO autorstwo VALUES (154, 'Gambin');
INSERT INTO autorstwo VALUES (155, 'Gambin');
INSERT INTO autorstwo VALUES (156, 'Chung');
INSERT INTO autorstwo VALUES (156, 'Gambin');
INSERT INTO autorstwo VALUES (156, 'Gogolewski');
INSERT INTO autorstwo VALUES (157, 'Gambin');
INSERT INTO autorstwo VALUES (157, 'Startek');
INSERT INTO autorstwo VALUES (158, 'Gambin');
INSERT INTO autorstwo VALUES (159, 'Górecki');
INSERT INTO autorstwo VALUES (160, 'Górecki');
INSERT INTO autorstwo VALUES (160, 'Paszek');
INSERT INTO autorstwo VALUES (161, 'Górecki');
INSERT INTO autorstwo VALUES (162, 'Górecki');
INSERT INTO autorstwo VALUES (163, 'Hofman');
INSERT INTO autorstwo VALUES (164, 'Iwanicki');
INSERT INTO autorstwo VALUES (165, 'Kaliszyk');
INSERT INTO autorstwo VALUES (166, 'Kaliszyk');
INSERT INTO autorstwo VALUES (167, 'Kaliszyk');
INSERT INTO autorstwo VALUES (168, 'Karczmarz');
INSERT INTO autorstwo VALUES (169, 'Karczmarz');
INSERT INTO autorstwo VALUES (169, 'Sankowski');
INSERT INTO autorstwo VALUES (170, 'Klin');
INSERT INTO autorstwo VALUES (171, 'Klin');
INSERT INTO autorstwo VALUES (172, 'Klin');
INSERT INTO autorstwo VALUES (173, 'Klin');
INSERT INTO autorstwo VALUES (174, 'Klin');
INSERT INTO autorstwo VALUES (174, 'Lasota');
INSERT INTO autorstwo VALUES (174, 'Toruńczyk');
INSERT INTO autorstwo VALUES (175, 'Kopczyński');
INSERT INTO autorstwo VALUES (176, 'Kowalik');
INSERT INTO autorstwo VALUES (177, 'Kowalik');
INSERT INTO autorstwo VALUES (177, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (177, 'Wrochna');
INSERT INTO autorstwo VALUES (178, 'Kowaluk');
INSERT INTO autorstwo VALUES (179, 'Kowaluk');
INSERT INTO autorstwo VALUES (180, 'Kozłowski');
INSERT INTO autorstwo VALUES (181, 'Michalak');
INSERT INTO autorstwo VALUES (181, 'Skibski');
INSERT INTO autorstwo VALUES (182, 'Michalak');
INSERT INTO autorstwo VALUES (182, 'Skibski');
INSERT INTO autorstwo VALUES (183, 'Michalak');
INSERT INTO autorstwo VALUES (184, 'Michalak');
INSERT INTO autorstwo VALUES (185, 'Michalak');
INSERT INTO autorstwo VALUES (185, 'Skibski');
INSERT INTO autorstwo VALUES (186, 'Michalak');
INSERT INTO autorstwo VALUES (187, 'Michalak');
INSERT INTO autorstwo VALUES (188, 'Mucha');
INSERT INTO autorstwo VALUES (188, 'Węgrzycki');
INSERT INTO autorstwo VALUES (188, 'Włodarczyk');
INSERT INTO autorstwo VALUES (189, 'Mucha');
INSERT INTO autorstwo VALUES (189, 'Pawlewicz');
INSERT INTO autorstwo VALUES (189, 'Węgrzycki');
INSERT INTO autorstwo VALUES (190, 'Murlak');
INSERT INTO autorstwo VALUES (191, 'Gogacz');
INSERT INTO autorstwo VALUES (191, 'Murlak');
INSERT INTO autorstwo VALUES (192, 'Górecki');
INSERT INTO autorstwo VALUES (193, 'Nguyen AL');
INSERT INTO autorstwo VALUES (194, 'Nguyen AL');
INSERT INTO autorstwo VALUES (195, 'Nguyen AL');
INSERT INTO autorstwo VALUES (196, 'Nguyen AL');
INSERT INTO autorstwo VALUES (197, 'Nguyen AL');
INSERT INTO autorstwo VALUES (198, 'Nguyen AL');
INSERT INTO autorstwo VALUES (199, 'Niemyska');
INSERT INTO autorstwo VALUES (200, 'Niemyska');
INSERT INTO autorstwo VALUES (201, 'Parys');
INSERT INTO autorstwo VALUES (202, 'Parys');
INSERT INTO autorstwo VALUES (203, 'Górecki');
INSERT INTO autorstwo VALUES (203, 'Paszek');
INSERT INTO autorstwo VALUES (204, 'Górecki');
INSERT INTO autorstwo VALUES (204, 'Paszek');
INSERT INTO autorstwo VALUES (205, 'Peczarski');
INSERT INTO autorstwo VALUES (206, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (207, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (208, 'Zych-Pawlewicz');
INSERT INTO autorstwo VALUES (209, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (209, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (210, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (210, 'Wrochna');
INSERT INTO autorstwo VALUES (211, 'Nadara');
INSERT INTO autorstwo VALUES (211, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (212, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (213, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (214, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (214, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (215, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (215, 'Sorge');
INSERT INTO autorstwo VALUES (216, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (216, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (217, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (218, 'Novotná');
INSERT INTO autorstwo VALUES (218, 'Okrasa');
INSERT INTO autorstwo VALUES (218, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (218, 'Rzążewski');
INSERT INTO autorstwo VALUES (219, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (219, 'Wrochna');
INSERT INTO autorstwo VALUES (220, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (221, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (222, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (223, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (223, 'Wrochna');
INSERT INTO autorstwo VALUES (224, 'Przybyłek');
INSERT INTO autorstwo VALUES (225, 'Radoszewski');
INSERT INTO autorstwo VALUES (225, 'Rytter');
INSERT INTO autorstwo VALUES (225, 'Straszyński');
INSERT INTO autorstwo VALUES (225, 'Waleń');
INSERT INTO autorstwo VALUES (226, 'Radoszewski');
INSERT INTO autorstwo VALUES (226, 'Rytter');
INSERT INTO autorstwo VALUES (226, 'Straszyński');
INSERT INTO autorstwo VALUES (226, 'Waleń');
INSERT INTO autorstwo VALUES (227, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (227, 'Radoszewski');
INSERT INTO autorstwo VALUES (227, 'Rytter');
INSERT INTO autorstwo VALUES (227, 'Straszyński');
INSERT INTO autorstwo VALUES (227, 'Waleń');
INSERT INTO autorstwo VALUES (228, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (228, 'Radoszewski');
INSERT INTO autorstwo VALUES (228, 'Rytter');
INSERT INTO autorstwo VALUES (228, 'Straszyński');
INSERT INTO autorstwo VALUES (228, 'Waleń');
INSERT INTO autorstwo VALUES (229, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (229, 'Radoszewski');
INSERT INTO autorstwo VALUES (230, 'Radoszewski');
INSERT INTO autorstwo VALUES (231, 'Radoszewski');
INSERT INTO autorstwo VALUES (232, 'Radoszewski');
INSERT INTO autorstwo VALUES (233, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (233, 'Radoszewski');
INSERT INTO autorstwo VALUES (234, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (234, 'Radoszewski');
INSERT INTO autorstwo VALUES (234, 'Rytter');
INSERT INTO autorstwo VALUES (234, 'Waleń');
INSERT INTO autorstwo VALUES (235, 'Rytter');
INSERT INTO autorstwo VALUES (236, 'Rządca');
INSERT INTO autorstwo VALUES (237, 'Sankowski');
INSERT INTO autorstwo VALUES (238, 'Skowron');
INSERT INTO autorstwo VALUES (239, 'Skowron');
INSERT INTO autorstwo VALUES (240, 'Skowron');
INSERT INTO autorstwo VALUES (241, 'Skowron');
INSERT INTO autorstwo VALUES (242, 'Skowron');
INSERT INTO autorstwo VALUES (243, 'Skowron');
INSERT INTO autorstwo VALUES (244, 'Chen');
INSERT INTO autorstwo VALUES (244, 'Skowron');
INSERT INTO autorstwo VALUES (244, 'Sorge');
INSERT INTO autorstwo VALUES (245, 'Skowron');
INSERT INTO autorstwo VALUES (246, 'Lhote');
INSERT INTO autorstwo VALUES (246, 'Michielini');
INSERT INTO autorstwo VALUES (246, 'Skrzypczak');
INSERT INTO autorstwo VALUES (247, 'Michalewski');
INSERT INTO autorstwo VALUES (247, 'Skrzypczak');
INSERT INTO autorstwo VALUES (248, 'Ślęzak');
INSERT INTO autorstwo VALUES (249, 'Ślęzak');
INSERT INTO autorstwo VALUES (250, 'Ślęzak');
INSERT INTO autorstwo VALUES (251, 'Szałas');
INSERT INTO autorstwo VALUES (252, 'Szałas');
INSERT INTO autorstwo VALUES (253, 'Szczurek');
INSERT INTO autorstwo VALUES (253, 'Tiuryn');
INSERT INTO autorstwo VALUES (254, 'Szczurek');
INSERT INTO autorstwo VALUES (255, 'Tuszyńska');
INSERT INTO autorstwo VALUES (255, 'Wilczyński');
INSERT INTO autorstwo VALUES (256, 'Skibski');
INSERT INTO autorstwo VALUES (257, 'Węgrzycki');
INSERT INTO autorstwo VALUES (258, 'Wilczyński');
INSERT INTO autorstwo VALUES (259, 'Włodarczyk');
INSERT INTO autorstwo VALUES (260, 'Włodarczyk');
INSERT INTO autorstwo VALUES (261, 'Adamczyk');
INSERT INTO autorstwo VALUES (261, 'Włodarczyk');
INSERT INTO autorstwo VALUES (262, 'Iwanicki');
INSERT INTO autorstwo VALUES (263, 'Biliński');
INSERT INTO autorstwo VALUES (264, 'Biliński');
INSERT INTO autorstwo VALUES (265, 'Bojańczyk');
INSERT INTO autorstwo VALUES (265, 'Kelmendi');
INSERT INTO autorstwo VALUES (265, 'Stefański');
INSERT INTO autorstwo VALUES (266, 'Bojańczyk');
INSERT INTO autorstwo VALUES (267, 'Bojańczyk');
INSERT INTO autorstwo VALUES (267, 'Stefański');
INSERT INTO autorstwo VALUES (268, 'Bojańczyk');
INSERT INTO autorstwo VALUES (268, 'Schmude');
INSERT INTO autorstwo VALUES (269, 'Bojańczyk');
INSERT INTO autorstwo VALUES (270, 'Cygan');
INSERT INTO autorstwo VALUES (271, 'Cygan');
INSERT INTO autorstwo VALUES (271, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (272, 'Czerwiński');
INSERT INTO autorstwo VALUES (273, 'Czerwiński');
INSERT INTO autorstwo VALUES (273, 'Lasota');
INSERT INTO autorstwo VALUES (274, 'Czerwiński');
INSERT INTO autorstwo VALUES (274, 'Hofman');
INSERT INTO autorstwo VALUES (275, 'Dojer');
INSERT INTO autorstwo VALUES (276, 'Dutta');
INSERT INTO autorstwo VALUES (277, 'Dziubiński');
INSERT INTO autorstwo VALUES (278, 'Dziubiński');
INSERT INTO autorstwo VALUES (279, 'Fleszar');
INSERT INTO autorstwo VALUES (280, 'Fleszar');
INSERT INTO autorstwo VALUES (281, 'Gambin');
INSERT INTO autorstwo VALUES (281, 'Gogolewski');
INSERT INTO autorstwo VALUES (282, 'Gambin');
INSERT INTO autorstwo VALUES (282, 'Startek');
INSERT INTO autorstwo VALUES (283, 'Gambin');
INSERT INTO autorstwo VALUES (284, 'Gambin');
INSERT INTO autorstwo VALUES (285, 'Gora');
INSERT INTO autorstwo VALUES (286, 'Górecki');
INSERT INTO autorstwo VALUES (287, 'Górecki');
INSERT INTO autorstwo VALUES (287, 'Paszek');
INSERT INTO autorstwo VALUES (287, 'Tiuryn');
INSERT INTO autorstwo VALUES (288, 'Hofman');
INSERT INTO autorstwo VALUES (289, 'Iwanicki');
INSERT INTO autorstwo VALUES (290, 'Janusz');
INSERT INTO autorstwo VALUES (290, 'Ślęzak');
INSERT INTO autorstwo VALUES (291, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (291, 'Karczmarz');
INSERT INTO autorstwo VALUES (292, 'Kołodziejski');
INSERT INTO autorstwo VALUES (293, 'Kowalik');
INSERT INTO autorstwo VALUES (293, 'Li');
INSERT INTO autorstwo VALUES (293, 'Nadara');
INSERT INTO autorstwo VALUES (293, 'Smulewicz');
INSERT INTO autorstwo VALUES (294, 'Kowalik');
INSERT INTO autorstwo VALUES (294, 'Majewski');
INSERT INTO autorstwo VALUES (295, 'Kowalik');
INSERT INTO autorstwo VALUES (295, 'Mucha');
INSERT INTO autorstwo VALUES (295, 'Nadara');
INSERT INTO autorstwo VALUES (295, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (295, 'Sorge');
INSERT INTO autorstwo VALUES (295, 'Wygocki');
INSERT INTO autorstwo VALUES (296, 'Kowaluk');
INSERT INTO autorstwo VALUES (297, 'Kozłowski');
INSERT INTO autorstwo VALUES (298, 'Lasota');
INSERT INTO autorstwo VALUES (299, 'Machnicka');
INSERT INTO autorstwo VALUES (300, 'Michalak');
INSERT INTO autorstwo VALUES (300, 'Skibski');
INSERT INTO autorstwo VALUES (301, 'Michalak');
INSERT INTO autorstwo VALUES (302, 'Michalak');
INSERT INTO autorstwo VALUES (303, 'Michalak');
INSERT INTO autorstwo VALUES (303, 'Skibski');
INSERT INTO autorstwo VALUES (304, 'Michalak');
INSERT INTO autorstwo VALUES (304, 'Skibski');
INSERT INTO autorstwo VALUES (305, 'Michalak');
INSERT INTO autorstwo VALUES (306, 'Mucha');
INSERT INTO autorstwo VALUES (306, 'Smulewicz');
INSERT INTO autorstwo VALUES (307, 'Gogacz');
INSERT INTO autorstwo VALUES (307, 'Murlak');
INSERT INTO autorstwo VALUES (308, 'Gogacz');
INSERT INTO autorstwo VALUES (308, 'Murlak');
INSERT INTO autorstwo VALUES (309, 'Nguyen AL');
INSERT INTO autorstwo VALUES (310, 'Nguyen AL');
INSERT INTO autorstwo VALUES (311, 'Niemyska');
INSERT INTO autorstwo VALUES (312, 'Niemyska');
INSERT INTO autorstwo VALUES (313, 'Niwiński');
INSERT INTO autorstwo VALUES (313, 'Skrzypczak');
INSERT INTO autorstwo VALUES (314, 'Niwiński');
INSERT INTO autorstwo VALUES (314, 'Parys');
INSERT INTO autorstwo VALUES (315, 'Parys');
INSERT INTO autorstwo VALUES (316, 'Parys');
INSERT INTO autorstwo VALUES (317, 'Barozzini');
INSERT INTO autorstwo VALUES (317, 'Clemente');
INSERT INTO autorstwo VALUES (317, 'Parys');
INSERT INTO autorstwo VALUES (318, 'Parys');
INSERT INTO autorstwo VALUES (319, 'Parys');
INSERT INTO autorstwo VALUES (320, 'Parys');
INSERT INTO autorstwo VALUES (321, 'Parys');
INSERT INTO autorstwo VALUES (322, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (322, 'Sorge');
INSERT INTO autorstwo VALUES (323, 'Bellitto');
INSERT INTO autorstwo VALUES (323, 'Li');
INSERT INTO autorstwo VALUES (323, 'Okrasa');
INSERT INTO autorstwo VALUES (323, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (323, 'Sorge');
INSERT INTO autorstwo VALUES (324, 'Li');
INSERT INTO autorstwo VALUES (324, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (325, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (325, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (326, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (326, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (327, 'Pilipczuk Ma');
INSERT INTO autorstwo VALUES (328, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (328, 'Węgrzycki');
INSERT INTO autorstwo VALUES (329, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (330, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (331, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (332, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (333, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (334, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (335, 'Gajarský');
INSERT INTO autorstwo VALUES (335, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (335, 'Toruńczyk');
INSERT INTO autorstwo VALUES (336, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (337, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (338, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (339, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (340, 'Pilipczuk Mi');
INSERT INTO autorstwo VALUES (340, 'Wrochna');
INSERT INTO autorstwo VALUES (341, 'Radoszewski');
INSERT INTO autorstwo VALUES (341, 'Rytter');
INSERT INTO autorstwo VALUES (341, 'Waleń');
INSERT INTO autorstwo VALUES (342, 'Radoszewski');
INSERT INTO autorstwo VALUES (343, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (343, 'Radoszewski');
INSERT INTO autorstwo VALUES (343, 'Rytter');
INSERT INTO autorstwo VALUES (343, 'Straszyński');
INSERT INTO autorstwo VALUES (343, 'Waleń');
INSERT INTO autorstwo VALUES (344, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (344, 'Radoszewski');
INSERT INTO autorstwo VALUES (345, 'Radoszewski');
INSERT INTO autorstwo VALUES (345, 'Straszyński');
INSERT INTO autorstwo VALUES (346, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (346, 'Radoszewski');
INSERT INTO autorstwo VALUES (346, 'Rytter');
INSERT INTO autorstwo VALUES (346, 'Waleń');
INSERT INTO autorstwo VALUES (347, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (347, 'Radoszewski');
INSERT INTO autorstwo VALUES (348, 'Radoszewski');
INSERT INTO autorstwo VALUES (349, 'Radoszewski');
INSERT INTO autorstwo VALUES (349, 'Rytter');
INSERT INTO autorstwo VALUES (349, 'Straszyński');
INSERT INTO autorstwo VALUES (349, 'Waleń');
INSERT INTO autorstwo VALUES (350, 'Radoszewski');
INSERT INTO autorstwo VALUES (350, 'Rytter');
INSERT INTO autorstwo VALUES (350, 'Straszyński');
INSERT INTO autorstwo VALUES (350, 'Waleń');
INSERT INTO autorstwo VALUES (351, 'Radoszewski');
INSERT INTO autorstwo VALUES (352, 'Radoszewski');
INSERT INTO autorstwo VALUES (352, 'Rytter');
INSERT INTO autorstwo VALUES (352, 'Waleń');
INSERT INTO autorstwo VALUES (353, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (353, 'Radoszewski');
INSERT INTO autorstwo VALUES (353, 'Rytter');
INSERT INTO autorstwo VALUES (353, 'Waleń');
INSERT INTO autorstwo VALUES (354, 'Charalampopoulos');
INSERT INTO autorstwo VALUES (354, 'Radoszewski');
INSERT INTO autorstwo VALUES (354, 'Waleń');
INSERT INTO autorstwo VALUES (355, 'Radoszewski');
INSERT INTO autorstwo VALUES (355, 'Rytter');
INSERT INTO autorstwo VALUES (355, 'Waleń');
INSERT INTO autorstwo VALUES (356, 'Radoszewski');
INSERT INTO autorstwo VALUES (357, 'Rządca');
INSERT INTO autorstwo VALUES (358, 'Rządca');
INSERT INTO autorstwo VALUES (359, 'Schmude');
INSERT INTO autorstwo VALUES (360, 'Skibski');
INSERT INTO autorstwo VALUES (361, 'Skowron');
INSERT INTO autorstwo VALUES (362, 'Skowron');
INSERT INTO autorstwo VALUES (363, 'Skowron');
INSERT INTO autorstwo VALUES (364, 'Skowron');
INSERT INTO autorstwo VALUES (365, 'Skowron');
INSERT INTO autorstwo VALUES (366, 'Skowron');
INSERT INTO autorstwo VALUES (367, 'Skowron');
INSERT INTO autorstwo VALUES (368, 'Skowron');
INSERT INTO autorstwo VALUES (369, 'Skrzypczak');
INSERT INTO autorstwo VALUES (370, 'Michielini');
INSERT INTO autorstwo VALUES (370, 'Skrzypczak');
INSERT INTO autorstwo VALUES (371, 'Fabiański');
INSERT INTO autorstwo VALUES (371, 'Skrzypczak');
INSERT INTO autorstwo VALUES (371, 'Toruńczyk');
INSERT INTO autorstwo VALUES (372, 'Ślęzak');
INSERT INTO autorstwo VALUES (373, 'Ślęzak');
INSERT INTO autorstwo VALUES (374, 'Ślęzak');
INSERT INTO autorstwo VALUES (375, 'Ślęzak');
INSERT INTO autorstwo VALUES (376, 'Ślęzak');
INSERT INTO autorstwo VALUES (377, 'Ślęzak');
INSERT INTO autorstwo VALUES (378, 'Startek');
INSERT INTO autorstwo VALUES (379, 'Startek');
INSERT INTO autorstwo VALUES (380, 'Szałas');
INSERT INTO autorstwo VALUES (381, 'Szałas');
INSERT INTO autorstwo VALUES (382, 'Szałas');
INSERT INTO autorstwo VALUES (383, 'Szczurek');
INSERT INTO autorstwo VALUES (384, 'Szczurek');
INSERT INTO autorstwo VALUES (385, 'Szczurek');
INSERT INTO autorstwo VALUES (386, 'Górecki');
INSERT INTO autorstwo VALUES (386, 'Tiuryn');
INSERT INTO autorstwo VALUES (387, 'Toruńczyk');
INSERT INTO autorstwo VALUES (388, 'Toruńczyk');
INSERT INTO autorstwo VALUES (389, 'Wilczyński');


CREATE TABLE autorzy (
	ID TEXT PRIMARY KEY,
	Ryzyko INTEGER NOT NULL,
	Sloty REAL NOT NULL
);


INSERT INTO autorzy VALUES ('Adamczyk', 1, 2.4);
INSERT INTO autorzy VALUES ('Barozzini', 1, 1.6);
INSERT INTO autorzy VALUES ('Bellitto', 0, 1.6);
INSERT INTO autorzy VALUES ('Biecek', 0, 1.78);
INSERT INTO autorzy VALUES ('Biliński', 1, 3.2);
INSERT INTO autorzy VALUES ('Bojańczyk', 1, 4);
INSERT INTO autorzy VALUES ('Celińska-Kopczyńska', 0, 2.4);
INSERT INTO autorzy VALUES ('Charalampopoulos', 0, 1);
INSERT INTO autorzy VALUES ('Chen', 0, 1);
INSERT INTO autorzy VALUES ('Chengot Sankaramenon', 0, 1.6);
INSERT INTO autorzy VALUES ('Chung', 1, 4);
INSERT INTO autorzy VALUES ('Clemente', 1, 4);
INSERT INTO autorzy VALUES ('Cygan', 1, 4);
INSERT INTO autorzy VALUES ('Cyranka', 0, 2.4);
INSERT INTO autorzy VALUES ('Czerwiński', 1, 4);
INSERT INTO autorzy VALUES ('Darvish Shafighi', 1, 2.4);
INSERT INTO autorzy VALUES ('Defrain', 0, 1);
INSERT INTO autorzy VALUES ('Diks', 1, 4);
INSERT INTO autorzy VALUES ('Dojer', 1, 4);
INSERT INTO autorzy VALUES ('Dross', 0, 1);
INSERT INTO autorzy VALUES ('Dunin-Kęplicz', 1, 4);
INSERT INTO autorzy VALUES ('Dutta', 0, 2.4);
INSERT INTO autorzy VALUES ('Dziembowski', 1, 4);
INSERT INTO autorzy VALUES ('Dziubiński', 1, 4);
INSERT INTO autorzy VALUES ('Fabiański', 0, 1.64);
INSERT INTO autorzy VALUES ('Fleszar', 1, 2.4);
INSERT INTO autorzy VALUES ('Gajarský', 0, 1);
INSERT INTO autorzy VALUES ('Gambin', 1, 4);
INSERT INTO autorzy VALUES ('Geniet', 0, 1);
INSERT INTO autorzy VALUES ('Gogacz', 1, 4);
INSERT INTO autorzy VALUES ('Gogolewski', 0, 1.76);
INSERT INTO autorzy VALUES ('Gora', 0, 1.6);
INSERT INTO autorzy VALUES ('Górecki', 1, 4);
INSERT INTO autorzy VALUES ('Hofman', 1, 4);
INSERT INTO autorzy VALUES ('Iwanicki', 1, 4);
INSERT INTO autorzy VALUES ('Jankowski', 0, 1.6);
INSERT INTO autorzy VALUES ('Janusz', 1, 4);
INSERT INTO autorzy VALUES ('Jaworski', 1, 2.4);
INSERT INTO autorzy VALUES ('Kaliszyk', 1, 1);
INSERT INTO autorzy VALUES ('Kang', 1, 2.4);
INSERT INTO autorzy VALUES ('Karczmarz', 1, 2.08);
INSERT INTO autorzy VALUES ('Kazana', 1, 2);
INSERT INTO autorzy VALUES ('Kelmendi', 0, 1);
INSERT INTO autorzy VALUES ('Kiefer', 0, 1);
INSERT INTO autorzy VALUES ('Klin', 1, 4);
INSERT INTO autorzy VALUES ('Kołodziejski', 1, 2.4);
INSERT INTO autorzy VALUES ('Kopczyński', 1, 4);
INSERT INTO autorzy VALUES ('Kowalik', 1, 4);
INSERT INTO autorzy VALUES ('Kowaluk', 1, 4);
INSERT INTO autorzy VALUES ('Kozłowski', 1, 3.2);
INSERT INTO autorzy VALUES ('Lasota', 1, 4);
INSERT INTO autorzy VALUES ('Lhote', 0, 1.6);
INSERT INTO autorzy VALUES ('Li', 1, 3.2);
INSERT INTO autorzy VALUES ('Machnicka', 1, 3.2);
INSERT INTO autorzy VALUES ('Majewski', 0, 1.44);
INSERT INTO autorzy VALUES ('Mari', 0, 1);
INSERT INTO autorzy VALUES ('Masařik', 0, 1.6);
INSERT INTO autorzy VALUES ('Michalak', 1, 4);
INSERT INTO autorzy VALUES ('Michalewski', 1, 1.25);
INSERT INTO autorzy VALUES ('Michielini', 1, 3.2);
INSERT INTO autorzy VALUES ('Mucha', 1, 4);
INSERT INTO autorzy VALUES ('Mukherjee', 0, 1.6);
INSERT INTO autorzy VALUES ('Murlak', 1, 4);
INSERT INTO autorzy VALUES ('Muzi', 0, 1.6);
INSERT INTO autorzy VALUES ('Nadara', 1, 2.4);
INSERT INTO autorzy VALUES ('Nguyen AL', 1, 4);
INSERT INTO autorzy VALUES ('Nguyen HS', 1, 4);
INSERT INTO autorzy VALUES ('Niemyska', 1, 4);
INSERT INTO autorzy VALUES ('Niwiński', 1, 4);
INSERT INTO autorzy VALUES ('Novotná', 0, 2.4);
INSERT INTO autorzy VALUES ('Nyporko', 0, 1);
INSERT INTO autorzy VALUES ('Odrzygóźdź', 0, 1);
INSERT INTO autorzy VALUES ('Okrasa', 0, 2.4);
INSERT INTO autorzy VALUES ('Pacuk', 0, 2);
INSERT INTO autorzy VALUES ('Parys', 1, 4);
INSERT INTO autorzy VALUES ('Paszek', 0, 1.6);
INSERT INTO autorzy VALUES ('Pawlewicz', 1, 4);
INSERT INTO autorzy VALUES ('Pilipczuk Ma', 1, 4);
INSERT INTO autorzy VALUES ('Pilipczuk Mi', 1, 4);
INSERT INTO autorzy VALUES ('Plandowski', 1, 4);
INSERT INTO autorzy VALUES ('Pratt-Hartmann', 0, 1);
INSERT INTO autorzy VALUES ('Przybylski', 0, 1.6);
INSERT INTO autorzy VALUES ('Przybyłek', 1, 2.4);
INSERT INTO autorzy VALUES ('Radoszewski', 1, 4);
INSERT INTO autorzy VALUES ('Rosa', 0, 1);
INSERT INTO autorzy VALUES ('Rutka', 0, 1.6);
INSERT INTO autorzy VALUES ('Rytter', 1, 2);
INSERT INTO autorzy VALUES ('Rządca', 1, 3.2);
INSERT INTO autorzy VALUES ('Rzążewski', 0, 1);
INSERT INTO autorzy VALUES ('Salamanca Tellez', 1, 4);
INSERT INTO autorzy VALUES ('Sankowski', 1, 4);
INSERT INTO autorzy VALUES ('Schmude', 1, 3.2);
INSERT INTO autorzy VALUES ('Schubert', 1, 4);
INSERT INTO autorzy VALUES ('Skibski', 1, 4);
INSERT INTO autorzy VALUES ('Skowron', 1, 3.2);
INSERT INTO autorzy VALUES ('Skrzypczak', 1, 4);
INSERT INTO autorzy VALUES ('Smulewicz', 1, 3.2);
INSERT INTO autorzy VALUES ('Sokołowski', 0, 1.44);
INSERT INTO autorzy VALUES ('Sorge', 0, 1.6);
INSERT INTO autorzy VALUES ('Sroka', 1, 4);
INSERT INTO autorzy VALUES ('Startek', 1, 4);
INSERT INTO autorzy VALUES ('Stefański', 0, 1.6);
INSERT INTO autorzy VALUES ('Stencel', 1, 4);
INSERT INTO autorzy VALUES ('Straszyński', 0, 1);
INSERT INTO autorzy VALUES ('Szałas', 1, 4);
INSERT INTO autorzy VALUES ('Szczurek', 1, 4);
INSERT INTO autorzy VALUES ('Ślęzak', 1, 4);
INSERT INTO autorzy VALUES ('Tarlecki', 1, 4);
INSERT INTO autorzy VALUES ('Tempczyk', 0, 1.4);
INSERT INTO autorzy VALUES ('Tiuryn', 1, 3.2);
INSERT INTO autorzy VALUES ('Toruńczyk', 1, 4);
INSERT INTO autorzy VALUES ('Tuszyńska', 1, 3.2);
INSERT INTO autorzy VALUES ('Tyszkiewicz', 1, 4);
INSERT INTO autorzy VALUES ('Urzyczyn', 1, 4);
INSERT INTO autorzy VALUES ('Vigny', 0, 1);
INSERT INTO autorzy VALUES ('Waleń', 1, 4);
INSERT INTO autorzy VALUES ('Wasilewski', 1, 4);
INSERT INTO autorzy VALUES ('Węgrzycki', 1, 2.88);
INSERT INTO autorzy VALUES ('Wilczyński', 1, 4);
INSERT INTO autorzy VALUES ('Witkowski', 0, 2.4);
INSERT INTO autorzy VALUES ('Włodarczyk', 1, 2.32);
INSERT INTO autorzy VALUES ('Wrochna', 0, 1);
INSERT INTO autorzy VALUES ('Wygocki', 1, 2.4);
INSERT INTO autorzy VALUES ('Zanka', 0, 1);
INSERT INTO autorzy VALUES ('Zych-Pawlewicz', 1, 4);


SELECT DISTINCT autorstwo1.Autor as "Pierwsza osoba", autorstwo2.Autor as "Druga osoba"
FROM autorstwo AS autorstwo1
JOIN autorzy ON autorstwo1.Autor = autorzy.ID
JOIN autorstwo AS autorstwo2 ON autorstwo1.Praca = autorstwo2.Praca
WHERE autorzy.Ryzyko = 1 AND autorstwo1.Autor <> autorstwo2.Autor AND autorstwo1.Autor NOT IN ( 
	SELECT DISTINCT Autorzy.id -- Osoby o ryzyku 1, które opublikowały pracę w 2020.
	FROM prace
	JOIN autorstwo ON prace.ID = autorstwo.praca
  	JOIN autorzy ON autorstwo.Autor = autorzy.ID
	WHERE ryzyko = 1 AND rok = 2020
);